In [7]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib qt

# p.s plotly is very good tool for 3d scatter

# 3d scatter

In [8]:
data = np.reshape(np.random.randn(90), (30,3))
print(data)

[[ 0.78968993  1.04269188  0.11314934]
 [-0.37899374  0.0161155   0.65164464]
 [-0.17620322  0.2677689   1.38501205]
 [ 0.49037694 -0.77052407 -1.04325464]
 [ 0.16551597 -0.1300414   0.32580041]
 [ 2.56260129 -0.34490098  0.85794594]
 [-0.51238419  0.94880649 -0.06154056]
 [ 0.78234063  0.29839656  0.19906861]
 [-0.06492853  1.37142054  2.46032167]
 [ 0.44482175 -0.69487756  0.95735112]
 [ 0.33281203 -1.66998367 -1.89552257]
 [ 1.53157867 -0.69538214  0.98123816]
 [ 0.88752239 -0.89922844  2.06657805]
 [ 1.0119909  -0.63461217  0.17374074]
 [ 0.23181597 -1.05659954 -1.64064535]
 [-0.12617877 -1.68275562 -0.38156765]
 [-2.21495814  0.22308144 -0.21088472]
 [-0.66722302 -1.05617394 -0.19577665]
 [-1.07515618 -0.02957205 -1.38761962]
 [-0.48953303  0.16508088  0.31207254]
 [ 0.88136482 -0.26904808  0.45951667]
 [-0.46185899 -0.46301311  1.0321701 ]
 [-0.91611752  1.04993917  1.08257163]
 [-1.46111491 -0.39451258 -1.24717638]
 [ 0.61145146 -0.54983718 -1.2200434 ]
 [ 0.85202767  1.56573047

In [9]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
for x in data:
    ax.scatter(x[0], x[1], x[2], marker="o")
plt.show()

In [15]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
sc = ax.scatter(data[:, 0], data[:, 1], data[:, 2], c=data[:, 0], marker="o")
plt.legend(*sc.legend_elements(), bbox_to_anchor=(1.05, 1), loc=2)
plt.show()

# 3d mesh

In [16]:
# Make data.
x = np.arange(-5, 5, 0.25)
y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(x, y)

# lambda (x, y)
Z = np.sin(np.sqrt(X**2 + Y**2))

In [18]:
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})

# Plot the surface.
surf = ax.plot_surface(X, Y, Z, cmap="magma",
                       linewidth=0, 
                       antialiased=False)

# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()